### ISSUE TITLE
[Docs]: Sendgrid email configuration

### ISSUE THREAD

**Issue by jnikhila** [appsmithorg/appsmith-docs#1468] opened 2023-07-13 11:50 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Documentation Link

https://docs.appsmith.com/getting-started/setup/instance-configuration/email/sendgrid

### Describe the problem and improvement.

Rehaul the doc.

**Comment by danciaclara** [comment] 2023-08-03 10:57
Duplicate of #1539

**Closed by danciaclara** 2023-08-03 10:57 UTC
Labels: Documentation, Doc Rehaul, User Education Pod
