### ISSUE TITLE
[Docs]: Update steps for SSO setup Active Directory

### ISSUE THREAD

**Issue by docs-appsmith** [appsmithorg/appsmith-docs#2225] opened 2024-04-24 11:43 UTC
## Problem Statement

To add new redirect urls for the  URLs that throw 404. Tagged by Google

## Other Relevant URLs

Draft: https://www.notion.so/Update-steps-for-SSO-setup-Active-Directory-cb2728e15c9e45ef8d03d9c7b6b7a786

**Comment by jnikhila** [comment] 2024-04-24 11:44
@trishaanand / @infinitetrooper - could you please add steps or pointers for update?

**Comment by jnikhila** [comment] 2024-04-26 04:38
duplicate of #2228 and #2229

**Closed** 2024-04-26 04:38 UTC
Labels: Documentation, Needs More Info, User Education Pod
