### ISSUE TITLE
[Docs]: Add cell borders property in Table widget

### ISSUE THREAD

**Issue by jsartisan** [appsmithorg/appsmith-docs#483] opened 2022-10-18 09:59 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Engineering Ticket Link

https://github.com/appsmithorg/appsmith/issues/10995

### Release Date

Already in release

**Comment by jnikhila** [comment] 2022-10-18 11:45
@jsartisan - Could you please share a first draft and the loom video for this?

**Comment by jsartisan** [comment] 2022-10-25 11:09
![image](https://user-images.githubusercontent.com/6636360/197757710-84afc9b0-6052-4723-86be-d55cdc154e52.png)
@jnikhila just added this style property and linked the PR that explains the property in the style section of table widget docs.

**Comment by somangshu** [comment] 2022-11-04 07:37
@jnikhila why is this issue not closed, the PR says the change is already added

**Comment by jnikhila** [comment] 2022-11-04 11:47
@somangshu - the issue is in the done pipeline, so it's completed. @spark-c - Is anything pending on this issue? Could we close it?

**Comment by spark-c** [comment] 2022-11-04 12:32
Resolved by #507

**Closed by spark-c** 2022-11-04 12:32 UTC
Labels: Documentation, Ready for Doc Team, User Education Pod
