### ISSUE TITLE
[Docs]: Send emails using the SMTP plugin -  How-to-guide

### ISSUE THREAD

**Issue by harshilp24** [appsmithorg/appsmith-docs#1824] opened 2023-10-19 05:52 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem and improvement.

Send emails using the SMTP plugin

**Comment by danciaclara** [comment] 2023-11-08 06:02
Duplicate of #1719

**Closed by danciaclara** 2023-11-08 06:02 UTC
Labels: Documentation, User Education Pod
