### ISSUE TITLE
[Docs]: Button Widget

### ISSUE THREAD

**Issue by jnikhila** [appsmithorg/appsmith-docs#667] opened 2022-12-09 12:19 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Documentation Link

https://docs.appsmith.com/reference/widgets/button

### Describe the problem

Restructuring

### Describe the improvement

Rehaul

**Comment by danciaclara** [comment] 2023-02-09 17:02
Duplicate of #20019

**Comment by danciaclara** [comment] 2023-02-09 17:07
@spark-c I see that you have opened a duplicate ticket on the other repo https://github.com/appsmithorg/appsmith/issues/20019 . Can you please close that and raise a PR for this one please?

**Closed** 2023-02-17 09:53 UTC
Labels: Documentation, Doc Rehaul, User Education Pod
