### ISSUE TITLE
[Task] Restructure and improve on 'Designing an Application' documentation

### ISSUE THREAD

**Issue by vuiets** [appsmithorg/appsmith-docs#331] opened 2022-01-20 15:08 UTC
Changes that we discussed for the _Working with Widgets_ page

Main things to do,
- [ ] Change structure to
```
├── Core Concepts
│   ├── Designing an Application
│   │   ├── Application Layout
│   │   ├── Working with Widgets
```

- [ ] Write an introductory _Designing an Application_ page
- [ ] Move content in _Designing an Application_ to _Working with Widgets_

Addtionally,
- [ ] Relook at title _Working with Widgets_; alternative is _Dragging and Dropping Widgets_
- [ ] Have the videos visually convey our message on a real app, could be on one of our _Example_ apps

**Comment by vuiets** [comment] 2022-01-20 15:14
@rahulramesha and @marks0351 tagging you here to keep you in the loop.

**Comment by jnikhila** [comment] 2022-05-25 09:49
Duplicate of #11887

**Closed by jnikhila** 2022-05-25 09:49 UTC
Labels: documentation, good first issue
