### ISSUE TITLE
[Docs]: Pass parameters to custom widget 

### ISSUE THREAD

**Issue by docs-appsmith** [appsmithorg/appsmith-docs#2214] opened 2024-04-17 08:49 UTC
## Problem Statement

To add new redirect urls for the  URLs that throw 404. Tagged by Google

## Other Relevant URLs

Draft: https://www.notion.so/Pass-parameters-to-custom-widget-f3113e83b7b34297865237a2397d53da

**Comment by jnikhila** [comment] 2024-04-17 11:33
Duplicate of https://github.com/appsmithorg/appsmith-docs/issues/2199

**Closed by jnikhila** 2024-04-17 11:33 UTC
Labels: Documentation, User Education Pod
