### ISSUE TITLE
[Docs]: Deploying and managing Appsmith in production

### ISSUE THREAD

**Issue by Pranay105** [appsmithorg/appsmith-docs#1370] opened 2023-06-15 10:35 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem and improvement.

- Add best practices for deploying and managing Appsmith within the production

**Comment by danciaclara** [comment] 2023-06-16 11:55
Duplicate of https://github.com/appsmithorg/appsmith-docs/issues/791

**Closed by danciaclara** 2023-06-16 11:55 UTC
Labels: Documentation, User Education Pod
