### ISSUE TITLE
[Docs]: Add troubleshooting guide for MongoDB config

### ISSUE THREAD

**Issue by docs-appsmith** [appsmithorg/appsmith-docs#2240] opened 2024-05-02 14:02 UTC
## Problem Statement

To add new redirect urls for the  URLs that throw 404. Tagged by Google

## Other Relevant URLs

Draft: https://www.notion.so/Add-troubleshooting-guide-for-MongoDB-config-9d6a8c8494564488938d195bebb9e77c

**Comment by jnikhila** [comment] 2024-05-02 14:03
Duplicate of #2237

**Closed by jnikhila** 2024-05-02 14:03 UTC
Labels: Documentation, User Education Pod
