### ISSUE TITLE
[Docs]: JSON Web tokens - Rehaul

### ISSUE THREAD

**Issue by Pranay105** [appsmithorg/appsmith-docs#1046] opened 2023-03-23 12:06 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Documentation Link

https://docs.appsmith.com/getting-started/setup/instance-configuration/authentication/json-web-tokens-jwt

### Describe the problem and improvement.

-

**Comment by jnikhila** [comment] 2023-04-20 10:53
duplicate of #782

**Closed by jnikhila** 2023-04-20 10:53 UTC
Labels: Documentation, User Education Pod
