### ISSUE TITLE
[Docs]: Widget Sidebar 

### ISSUE THREAD

**Issue by harshilp24** [appsmithorg/appsmith-docs#1531] opened 2023-07-27 11:29 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem and improvement.

[Docs]: Widget Sidebar

**Comment by danciaclara** [comment] 2023-08-16 05:52
Duplicate of #1604

**Closed by danciaclara** 2023-08-16 05:52 UTC
Labels: Documentation, User Education Pod
